#!/usr/bin/env python3
"""
Read results/*.json and emit a single summary.md ready to paste into the
dolang README, a blog post, or a conference deck.

Philosophy: no cherry-picking. Print every endpoint, every percentile, even
the ones where dolang loses. Credibility > PR.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def load_measure(results: Path, name: str) -> dict | None:
    p = results / f"{name}-measure.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def load_all_load(results: Path, name: str) -> list[tuple[str, dict]]:
    out = []
    for p in sorted(results.glob(f"{name}-load-*.json")):
        endpoint = p.stem.removeprefix(f"{name}-load-").replace("_", "/")
        try:
            out.append((endpoint, json.loads(p.read_text())))
        except Exception:
            pass
    return out


def fmt_us(v) -> str:
    if v is None:
        return "—"
    if v < 1000:
        return f"{v}μs"
    return f"{v/1000:.2f}ms"


def fmt_kb(v) -> str:
    if v is None:
        return "—"
    mb = v / 1024
    return f"{mb:.1f} MB"


def main() -> None:
    results = Path(sys.argv[1] if len(sys.argv) > 1 else "results")
    targets = ["dolang", "fastapi", "hono"]

    print("# HTTP Service Benchmark: dolang vs FastAPI vs Hono")
    print()
    print("Generated by `benches/http-comparison/harness/run_all.sh`. "
          "All three servers implement identical endpoints and were measured on "
          "the same machine with the same client harness.")
    print()

    # --- Cold start + RSS ---
    print("## Cold Start & Resident Memory")
    print()
    print("| Target  | Cold Start | RSS (median after warmup) |")
    print("|---------|-----------:|--------------------------:|")
    for t in targets:
        m = load_measure(results, t)
        if not m or "error" in (m or {}):
            print(f"| {t} | — | — |")
            continue
        cs = m.get("cold_start_s")
        rss = m.get("rss_kb_median")
        cs_str = f"{cs*1000:.0f} ms" if cs is not None else "—"
        print(f"| {t} | {cs_str} | {fmt_kb(rss)} |")
    print()

    # --- Load test per endpoint ---
    endpoints: dict[str, dict[str, dict]] = {}
    for t in targets:
        for ep, data in load_all_load(results, t):
            endpoints.setdefault(ep, {})[t] = data

    for ep, per_target in endpoints.items():
        print(f"## Load Test: `/{ep}`")
        print()
        any_data = next(iter(per_target.values()), None)
        if any_data:
            print(f"- Duration: {any_data['duration_s']}s, "
                  f"warmup {any_data['warmup_s']}s, "
                  f"connections: {any_data['connections']}")
            print()
        print("| Target  | QPS | p50 | p90 | p99 | Errors |")
        print("|---------|----:|----:|----:|----:|-------:|")
        for t in targets:
            d = per_target.get(t)
            if not d:
                print(f"| {t} | — | — | — | — | — |")
                continue
            lat = d["latency_us"]
            print(f"| {t} | {d['qps']:.0f} | {fmt_us(lat['p50'])} | "
                  f"{fmt_us(lat['p90'])} | {fmt_us(lat['p99'])} | {d['errors']} |")
        print()

    # --- Methodology / caveats ---
    print("## Methodology")
    print()
    print("- **Hardware/OS**: whatever machine you ran this on. "
          "Include `sw_vers` / `uname -a` when you publish results.")
    print("- **Endpoints**: `/hello` (static JSON) and `/greet/:name` (path param + concat). "
          "Both return a ~30-byte JSON body.")
    print("- **Client**: pure-Python asyncio load tester. "
          "Underestimates absolute ceiling vs wrk/bombardier; "
          "valid for *relative* comparison because all three servers face the same client.")
    print("- **Warmup**: 3 seconds of traffic before the measurement window, then 30s measurement.")
    print("- **Concurrency**: 64 persistent keep-alive connections, no pipelining.")
    print("- **Default server config**: single process, default settings. "
          "No uvicorn `--workers`, no Node cluster, no dolang worker tuning. "
          "This is the 'fresh out of the box' story.")
    print()
    print("## What this benchmark does NOT measure")
    print()
    print("- DB-in-the-loop latency (the bottleneck in real apps is usually Postgres, not the framework)")
    print("- Cold start under realistic dependency load (middlewares, ORM init, migrations)")
    print("- Memory behaviour under sustained high load / long uptime")
    print("- Accuracy of the framework's router on 100+ routes with wildcards")
    print("- Throughput under TLS / HTTP/2")
    print()
    print("Before you cite these numbers in a blog post, re-run with wrk and publish both sets.")


if __name__ == "__main__":
    main()
