#!/usr/bin/env bash
# Orchestrator: measure cold start + RSS + QPS/latency for dolang, FastAPI, Hono.
#
# Must run on macOS or Linux. Requires:
#   - Python 3.9+
#   - Node 18+ (for Hono)
#   - dolang release binary (we build it if missing)
#
# Output:
#   results/<target>-measure.json   (cold start + RSS)
#   results/<target>-load-<url>.json (load test per endpoint)
#   results/summary.md              (final report — generated by collate.py)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$ROOT/../.." && pwd)"
RESULTS="$ROOT/results"
HARNESS="$ROOT/harness"
PORT=8080

DURATION="${DURATION:-30}"
WARMUP="${WARMUP:-3}"
CONNECTIONS="${CONNECTIONS:-64}"

mkdir -p "$RESULTS"
rm -f "$RESULTS"/*.json "$RESULTS"/summary.md 2>/dev/null || true

# ---- helpers ----
log() { printf "\033[36m[%s]\033[0m %s\n" "$(date +%H:%M:%S)" "$*" >&2; }
die() { printf "\033[31mERROR:\033[0m %s\n" "$*" >&2; exit 1; }

wait_port_free() {
  local tries=30
  while (( tries-- > 0 )); do
    if ! nc -z 127.0.0.1 "$PORT" 2>/dev/null; then return 0; fi
    sleep 0.3
  done
  die "port $PORT still busy"
}

# ---- pre-flight ----
command -v python3 >/dev/null || die "python3 not found"
command -v node    >/dev/null || die "node not found"
command -v nc      >/dev/null || die "nc not found (used to probe port)"

# Build dolang if the release binary isn't present
DOLANG_BIN="$REPO_ROOT/target/release/dolang"
if [[ ! -x "$DOLANG_BIN" ]]; then
  log "dolang release binary not found; running 'cargo build --release' (this takes a while)..."
  ( cd "$REPO_ROOT" && cargo build --release )
fi

# Python venv for FastAPI — check the actual binary, not just the dir.
# Previous runs can leave a half-built venv behind.
VENV="$ROOT/fastapi/.venv"
if [[ ! -x "$VENV/bin/uvicorn" ]]; then
  log "setting up FastAPI venv (may take 30-60s)..."
  [[ -d "$VENV" ]] && rm -rf "$VENV"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --upgrade pip >/dev/null 2>&1 || true
  if ! "$VENV/bin/pip" install -r "$ROOT/fastapi/requirements.txt"; then
    die "FastAPI pip install failed. Check your network / Python version (need 3.9+)."
  fi
  [[ -x "$VENV/bin/uvicorn" ]] || die "pip install succeeded but uvicorn not found at $VENV/bin/uvicorn"
fi

# npm install for Hono — check for hono package, not just the dir
if [[ ! -d "$ROOT/hono/node_modules/hono" ]]; then
  log "installing Hono deps..."
  ( cd "$ROOT/hono" && npm install --no-audit --no-fund ) || die "npm install failed"
fi

# ---- measurement loop ----
run_target() {
  local name="$1" cwd="$2" cmd="$3"

  wait_port_free

  log "== $name =="
  log "measuring cold start + RSS..."
  python3 "$HARNESS/measure.py" \
    --name "$name" \
    --cwd "$cwd" \
    --cmd "$cmd" \
    --health "http://127.0.0.1:$PORT/health" \
    --warmup-url "http://127.0.0.1:$PORT/hello" \
    > "$RESULTS/$name-measure.json"

  # Relaunch for load test (measure.py tears down after sampling).
  # Redirect stderr from the subshell to /dev/null so the SIGTERM during
  # teardown doesn't print "Terminated: 15" noise to the user's terminal.
  wait_port_free
  ( cd "$cwd" && exec $cmd ) >/dev/null 2>&1 &
  local server_pid=$!
  disown $server_pid 2>/dev/null || true
  # Wait for server
  local ready=false
  for _ in $(seq 1 60); do
    if curl -sf "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; then ready=true; break; fi
    sleep 0.2
  done
  if ! $ready; then
    log "WARN: $name did not become ready within 12s; load test will likely error"
  fi

  for ep in hello greet/Alice; do
    local safe="${ep//\//_}"
    log "load test /$ep ..."
    python3 "$HARNESS/load_test.py" \
      --url "http://127.0.0.1:$PORT/$ep" \
      --duration "$DURATION" \
      --warmup "$WARMUP" \
      --connections "$CONNECTIONS" \
      --json \
      > "$RESULTS/$name-load-$safe.json"
  done

  # Tear down. Suppress shell job notifications so "Terminated: 15" stays
  # out of the user's terminal.
  { kill "$server_pid" 2>/dev/null; wait "$server_pid" 2>/dev/null; } || true
  # Kill any stragglers on the port (uvicorn workers, Node child processes, etc.)
  if command -v lsof >/dev/null; then
    local stragglers
    stragglers=$(lsof -ti tcp:$PORT 2>/dev/null || true)
    if [[ -n "$stragglers" ]]; then
      kill $stragglers 2>/dev/null || true
      sleep 0.3
      stragglers=$(lsof -ti tcp:$PORT 2>/dev/null || true)
      [[ -n "$stragglers" ]] && kill -9 $stragglers 2>/dev/null || true
    fi
  fi
  sleep 0.5
}

# Initial cleanup: kill anything currently bound to our port
if command -v lsof >/dev/null; then
  existing=$(lsof -ti tcp:$PORT 2>/dev/null || true)
  if [[ -n "$existing" ]]; then
    log "port $PORT busy on entry; killing PIDs: $existing"
    kill -9 $existing 2>/dev/null || true
    sleep 0.5
  fi
fi

# ---- targets ----
run_target "dolang" \
  "$ROOT/dolang" \
  "$DOLANG_BIN serve ."

run_target "fastapi" \
  "$ROOT/fastapi" \
  "$VENV/bin/uvicorn app:app --host 127.0.0.1 --port $PORT --log-level warning"

run_target "hono" \
  "$ROOT/hono" \
  "node app.js"

# ---- collate ----
log "generating summary.md ..."
python3 "$HARNESS/collate.py" "$RESULTS" > "$RESULTS/summary.md"
log "done. See $RESULTS/summary.md"
