// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: datanest.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataNestService_CreateNote_FullMethodName      = "/datanest.v1.DataNestService/CreateNote"
	DataNestService_GetNote_FullMethodName         = "/datanest.v1.DataNestService/GetNote"
	DataNestService_ListNotes_FullMethodName       = "/datanest.v1.DataNestService/ListNotes"
	DataNestService_SearchNotes_FullMethodName     = "/datanest.v1.DataNestService/SearchNotes"
	DataNestService_CreateTag_FullMethodName       = "/datanest.v1.DataNestService/CreateTag"
	DataNestService_ListTags_FullMethodName        = "/datanest.v1.DataNestService/ListTags"
	DataNestService_AttachTagToNote_FullMethodName = "/datanest.v1.DataNestService/AttachTagToNote"
)

// DataNestServiceClient is the client API for DataNestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNestServiceClient interface {
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*NoteDetail, error)
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*NoteDetail, error)
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*Tag, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	AttachTagToNote(ctx context.Context, in *AttachTagToNoteRequest, opts ...grpc.CallOption) (*NoteDetail, error)
}

type dataNestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNestServiceClient(cc grpc.ClientConnInterface) DataNestServiceClient {
	return &dataNestServiceClient{cc}
}

func (c *dataNestServiceClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*NoteDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteDetail)
	err := c.cc.Invoke(ctx, DataNestService_CreateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNestServiceClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*NoteDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteDetail)
	err := c.cc.Invoke(ctx, DataNestService_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNestServiceClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, DataNestService_ListNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNestServiceClient) SearchNotes(ctx context.Context, in *SearchNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, DataNestService_SearchNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNestServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tag)
	err := c.cc.Invoke(ctx, DataNestService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNestServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, DataNestService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataNestServiceClient) AttachTagToNote(ctx context.Context, in *AttachTagToNoteRequest, opts ...grpc.CallOption) (*NoteDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteDetail)
	err := c.cc.Invoke(ctx, DataNestService_AttachTagToNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataNestServiceServer is the server API for DataNestService service.
// All implementations must embed UnimplementedDataNestServiceServer
// for forward compatibility.
type DataNestServiceServer interface {
	CreateNote(context.Context, *CreateNoteRequest) (*NoteDetail, error)
	GetNote(context.Context, *GetNoteRequest) (*NoteDetail, error)
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	SearchNotes(context.Context, *SearchNotesRequest) (*ListNotesResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*Tag, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	AttachTagToNote(context.Context, *AttachTagToNoteRequest) (*NoteDetail, error)
	mustEmbedUnimplementedDataNestServiceServer()
}

// UnimplementedDataNestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataNestServiceServer struct{}

func (UnimplementedDataNestServiceServer) CreateNote(context.Context, *CreateNoteRequest) (*NoteDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedDataNestServiceServer) GetNote(context.Context, *GetNoteRequest) (*NoteDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedDataNestServiceServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedDataNestServiceServer) SearchNotes(context.Context, *SearchNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchNotes not implemented")
}
func (UnimplementedDataNestServiceServer) CreateTag(context.Context, *CreateTagRequest) (*Tag, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedDataNestServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedDataNestServiceServer) AttachTagToNote(context.Context, *AttachTagToNoteRequest) (*NoteDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachTagToNote not implemented")
}
func (UnimplementedDataNestServiceServer) mustEmbedUnimplementedDataNestServiceServer() {}
func (UnimplementedDataNestServiceServer) testEmbeddedByValue()                         {}

// UnsafeDataNestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNestServiceServer will
// result in compilation errors.
type UnsafeDataNestServiceServer interface {
	mustEmbedUnimplementedDataNestServiceServer()
}

func RegisterDataNestServiceServer(s grpc.ServiceRegistrar, srv DataNestServiceServer) {
	// If the following call panics, it indicates UnimplementedDataNestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataNestService_ServiceDesc, srv)
}

func _DataNestService_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNestServiceServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNestService_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNestServiceServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNestService_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNestServiceServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNestService_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNestServiceServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNestService_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNestServiceServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNestService_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNestServiceServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNestService_SearchNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNestServiceServer).SearchNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNestService_SearchNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNestServiceServer).SearchNotes(ctx, req.(*SearchNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNestService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNestServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNestService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNestServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNestService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNestServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNestService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNestServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataNestService_AttachTagToNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachTagToNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataNestServiceServer).AttachTagToNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataNestService_AttachTagToNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataNestServiceServer).AttachTagToNote(ctx, req.(*AttachTagToNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataNestService_ServiceDesc is the grpc.ServiceDesc for DataNestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datanest.v1.DataNestService",
	HandlerType: (*DataNestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _DataNestService_CreateNote_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _DataNestService_GetNote_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _DataNestService_ListNotes_Handler,
		},
		{
			MethodName: "SearchNotes",
			Handler:    _DataNestService_SearchNotes_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _DataNestService_CreateTag_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _DataNestService_ListTags_Handler,
		},
		{
			MethodName: "AttachTagToNote",
			Handler:    _DataNestService_AttachTagToNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datanest.proto",
}
