// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: datanest.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         string                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_datanest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Tag) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type NoteSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NoteId         string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ContentPreview string                 `protobuf:"bytes,3,opt,name=content_preview,json=contentPreview,proto3" json:"content_preview,omitempty"`
	UserId         string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NoteSummary) Reset() {
	*x = NoteSummary{}
	mi := &file_datanest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteSummary) ProtoMessage() {}

func (x *NoteSummary) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteSummary.ProtoReflect.Descriptor instead.
func (*NoteSummary) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{1}
}

func (x *NoteSummary) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteSummary) GetContentPreview() string {
	if x != nil {
		return x.ContentPreview
	}
	return ""
}

func (x *NoteSummary) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoteSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NoteSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type NoteDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteDetail) Reset() {
	*x = NoteDetail{}
	mi := &file_datanest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteDetail) ProtoMessage() {}

func (x *NoteDetail) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteDetail.ProtoReflect.Descriptor instead.
func (*NoteDetail) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{2}
}

func (x *NoteDetail) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoteDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoteDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NoteDetail) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *NoteDetail) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_datanest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNoteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteRequest) Reset() {
	*x = GetNoteRequest{}
	mi := &file_datanest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteRequest) ProtoMessage() {}

func (x *GetNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteRequest.ProtoReflect.Descriptor instead.
func (*GetNoteRequest) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{4}
}

func (x *GetNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type ListNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesRequest) Reset() {
	*x = ListNotesRequest{}
	mi := &file_datanest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesRequest) ProtoMessage() {}

func (x *ListNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesRequest.ProtoReflect.Descriptor instead.
func (*ListNotesRequest) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{5}
}

type SearchNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNotesRequest) Reset() {
	*x = SearchNotesRequest{}
	mi := &file_datanest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNotesRequest) ProtoMessage() {}

func (x *SearchNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNotesRequest.ProtoReflect.Descriptor instead.
func (*SearchNotesRequest) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{6}
}

func (x *SearchNotesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ListNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*NoteSummary         `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotesResponse) Reset() {
	*x = ListNotesResponse{}
	mi := &file_datanest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotesResponse) ProtoMessage() {}

func (x *ListNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotesResponse.ProtoReflect.Descriptor instead.
func (*ListNotesResponse) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{7}
}

func (x *ListNotesResponse) GetNotes() []*NoteSummary {
	if x != nil {
		return x.Notes
	}
	return nil
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_datanest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_datanest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{9}
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_datanest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{10}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type AttachTagToNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	TagId         string                 `protobuf:"bytes,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachTagToNoteRequest) Reset() {
	*x = AttachTagToNoteRequest{}
	mi := &file_datanest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachTagToNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachTagToNoteRequest) ProtoMessage() {}

func (x *AttachTagToNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datanest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachTagToNoteRequest.ProtoReflect.Descriptor instead.
func (*AttachTagToNoteRequest) Descriptor() ([]byte, []int) {
	return file_datanest_proto_rawDescGZIP(), []int{11}
}

func (x *AttachTagToNoteRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *AttachTagToNoteRequest) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

var File_datanest_proto protoreflect.FileDescriptor

const file_datanest_proto_rawDesc = "" +
	"\n" +
	"\x0edatanest.proto\x12\vdatanest.v1\"h\n" +
	"\x03Tag\x12\x15\n" +
	"\x06tag_id\x18\x01 \x01(\tR\x05tagId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\xbc\x01\n" +
	"\vNoteSummary\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\x0fcontent_preview\x18\x03 \x01(\tR\x0econtentPreview\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xd2\x01\n" +
	"\n" +
	"NoteDetail\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12$\n" +
	"\x04tags\x18\a \x03(\v2\x10.datanest.v1.TagR\x04tags\"C\n" +
	"\x11CreateNoteRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\")\n" +
	"\x0eGetNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\"\x12\n" +
	"\x10ListNotesRequest\"*\n" +
	"\x12SearchNotesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"C\n" +
	"\x11ListNotesResponse\x12.\n" +
	"\x05notes\x18\x01 \x03(\v2\x18.datanest.v1.NoteSummaryR\x05notes\"&\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x11\n" +
	"\x0fListTagsRequest\"8\n" +
	"\x10ListTagsResponse\x12$\n" +
	"\x04tags\x18\x01 \x03(\v2\x10.datanest.v1.TagR\x04tags\"H\n" +
	"\x16AttachTagToNoteRequest\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\tR\x05tagId2\x8d\x04\n" +
	"\x0fDataNestService\x12E\n" +
	"\n" +
	"CreateNote\x12\x1e.datanest.v1.CreateNoteRequest\x1a\x17.datanest.v1.NoteDetail\x12?\n" +
	"\aGetNote\x12\x1b.datanest.v1.GetNoteRequest\x1a\x17.datanest.v1.NoteDetail\x12J\n" +
	"\tListNotes\x12\x1d.datanest.v1.ListNotesRequest\x1a\x1e.datanest.v1.ListNotesResponse\x12N\n" +
	"\vSearchNotes\x12\x1f.datanest.v1.SearchNotesRequest\x1a\x1e.datanest.v1.ListNotesResponse\x12<\n" +
	"\tCreateTag\x12\x1d.datanest.v1.CreateTagRequest\x1a\x10.datanest.v1.Tag\x12G\n" +
	"\bListTags\x12\x1c.datanest.v1.ListTagsRequest\x1a\x1d.datanest.v1.ListTagsResponse\x12O\n" +
	"\x0fAttachTagToNote\x12#.datanest.v1.AttachTagToNoteRequest\x1a\x17.datanest.v1.NoteDetailB$Z\"datanest/go-service/internal/pb;pbb\x06proto3"

var (
	file_datanest_proto_rawDescOnce sync.Once
	file_datanest_proto_rawDescData []byte
)

func file_datanest_proto_rawDescGZIP() []byte {
	file_datanest_proto_rawDescOnce.Do(func() {
		file_datanest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datanest_proto_rawDesc), len(file_datanest_proto_rawDesc)))
	})
	return file_datanest_proto_rawDescData
}

var file_datanest_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_datanest_proto_goTypes = []any{
	(*Tag)(nil),                    // 0: datanest.v1.Tag
	(*NoteSummary)(nil),            // 1: datanest.v1.NoteSummary
	(*NoteDetail)(nil),             // 2: datanest.v1.NoteDetail
	(*CreateNoteRequest)(nil),      // 3: datanest.v1.CreateNoteRequest
	(*GetNoteRequest)(nil),         // 4: datanest.v1.GetNoteRequest
	(*ListNotesRequest)(nil),       // 5: datanest.v1.ListNotesRequest
	(*SearchNotesRequest)(nil),     // 6: datanest.v1.SearchNotesRequest
	(*ListNotesResponse)(nil),      // 7: datanest.v1.ListNotesResponse
	(*CreateTagRequest)(nil),       // 8: datanest.v1.CreateTagRequest
	(*ListTagsRequest)(nil),        // 9: datanest.v1.ListTagsRequest
	(*ListTagsResponse)(nil),       // 10: datanest.v1.ListTagsResponse
	(*AttachTagToNoteRequest)(nil), // 11: datanest.v1.AttachTagToNoteRequest
}
var file_datanest_proto_depIdxs = []int32{
	0,  // 0: datanest.v1.NoteDetail.tags:type_name -> datanest.v1.Tag
	1,  // 1: datanest.v1.ListNotesResponse.notes:type_name -> datanest.v1.NoteSummary
	0,  // 2: datanest.v1.ListTagsResponse.tags:type_name -> datanest.v1.Tag
	3,  // 3: datanest.v1.DataNestService.CreateNote:input_type -> datanest.v1.CreateNoteRequest
	4,  // 4: datanest.v1.DataNestService.GetNote:input_type -> datanest.v1.GetNoteRequest
	5,  // 5: datanest.v1.DataNestService.ListNotes:input_type -> datanest.v1.ListNotesRequest
	6,  // 6: datanest.v1.DataNestService.SearchNotes:input_type -> datanest.v1.SearchNotesRequest
	8,  // 7: datanest.v1.DataNestService.CreateTag:input_type -> datanest.v1.CreateTagRequest
	9,  // 8: datanest.v1.DataNestService.ListTags:input_type -> datanest.v1.ListTagsRequest
	11, // 9: datanest.v1.DataNestService.AttachTagToNote:input_type -> datanest.v1.AttachTagToNoteRequest
	2,  // 10: datanest.v1.DataNestService.CreateNote:output_type -> datanest.v1.NoteDetail
	2,  // 11: datanest.v1.DataNestService.GetNote:output_type -> datanest.v1.NoteDetail
	7,  // 12: datanest.v1.DataNestService.ListNotes:output_type -> datanest.v1.ListNotesResponse
	7,  // 13: datanest.v1.DataNestService.SearchNotes:output_type -> datanest.v1.ListNotesResponse
	0,  // 14: datanest.v1.DataNestService.CreateTag:output_type -> datanest.v1.Tag
	10, // 15: datanest.v1.DataNestService.ListTags:output_type -> datanest.v1.ListTagsResponse
	2,  // 16: datanest.v1.DataNestService.AttachTagToNote:output_type -> datanest.v1.NoteDetail
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_datanest_proto_init() }
func file_datanest_proto_init() {
	if File_datanest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datanest_proto_rawDesc), len(file_datanest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datanest_proto_goTypes,
		DependencyIndexes: file_datanest_proto_depIdxs,
		MessageInfos:      file_datanest_proto_msgTypes,
	}.Build()
	File_datanest_proto = out.File
	file_datanest_proto_goTypes = nil
	file_datanest_proto_depIdxs = nil
}
